# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a10d2e72553667afbe6b13c12e843979d807da8340fefae4bfec78c2ad9e851bd78e527940f7d3c3a885766ead24856dae2146b7ff5386fbd0342896d93c545a

test:
  secret_key_base: 1e50999f0482f3fcddf736e75d92f60d0658773a0edb888681d8633ae0a118353556571f962172a256b3893fa05703e428c299f3551fb62b8c7db21eebd0df81

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
